name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  analyze_test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter Pub Get
        run: |
          cd eisen
          flutter pub get
      - name: Analyze
        run: |
          cd eisen
          flutter analyze
      - name: Test
        run: |
          cd eisen
          flutter test --no-pub
      - name: Build Web
        run: |
          cd eisen
          flutter build web --no-tree-shake-icons --release
