arb-dir: l10n
template-arb-file: app_en.arb
output-dir: lib/l10n
output-class: AppLocalizations
untranslated-messages-file: l10n/untranslated.txt
nullable-getter: false
preferred-supported-locales:
  - en
  - es
